version: "3"
services:
  jekyll:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
    command: >
      bundle exec jekyll serve --host 0.0.0.0 --port 8080


      